version: '1'

services:
  client:
    build: .
    ports:
      - 3000:3000
    environment:
      - WATCHPACK_POLLING=true
    env_file:
      # Add .env rcpch api key
      - .env 
    command: >
      sh -c "npm start"
