# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - rcpch-dgc-react-client-unstable

on:
  push:
    branches:
      - unstable

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
      env:
        REACT_APP_GROWTH_API_BASEURL: ${{ secrets.REACT_APP_UNSTABLE_GROWTH_API_BASEURL }}

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'rcpch-dgc-react-client-unstable'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_29347588379c4b79b5ecb60c44811f67 }}
        package: .
